server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #链接这个地址的eureka进行心跳检查
  instance:
    prefer-ip-address: true   #以ip地址的方式注册进eureka中
spring:
  application:
    name:  ZUUL-GATEWAY   #将此应用程序，模块命名
zuul:
  prefix: /services  #指定一个全局前缀servers
  ignored-services: "*"  # 忽略指定微服务，多个微服务之间使用逗号分隔
  routes:
    system:
      path: /system/**
      serviceId: SYSTEM-SERVICE
    course:
      path: /course/**
      serviceId: COURSE-SERVICE